FROM grafana/grafana:latest-ubuntu

# ------------------------------------------------------
# 패키지 설치시작 - root 계정 사용
USER root
RUN apt-get update && apt-get install -y wget unzip bash

# 한글 폰트 설치
RUN apt-get install -y fontconfig
RUN mkdir -p /usr/share/fonts/nanumfont
RUN wget http://cdn.naver.com/naver/NanumFont/fontfiles/NanumFont_TTF_ALL.zip
RUN unzip NanumFont_TTF_ALL.zip -d /usr/share/fonts/nanumfont
RUN fc-cache -f && rm -rf /var/cache/*

# 시간대 설정
RUN apt-get install -y tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone

# ------------------------------------------------------
# 패키지 설치완료 - grafana 계정 사용
USER 472