FROM ubuntu/postgres:14-22.04_beta

ENV TZ=Asia/Seoul
ENV POSTGRES_INITDB_ARGS="--encoding=UTF-8"
ENV ALLOW_IP_RANGE=0.0.0.0/0

RUN apt-get update -y
RUN apt-get install git make gcc postgresql-server-dev-14 -y && \
    cd /tmp && git clone --branch v0.7.2 https://github.com/pgvector/pgvector.git
RUN cd /tmp/pgvector && make && make install 