FROM node:23.5.0-alpine3.21

RUN apk update

# 한글 폰트 설치
RUN apk --update add fontconfig
RUN mkdir -p /usr/share/fonts/nanumfont
RUN wget http://cdn.naver.com/naver/NanumFont/fontfiles/NanumFont_TTF_ALL.zip
RUN unzip NanumFont_TTF_ALL.zip -d /usr/share/fonts/nanumfont
RUN fc-cache -f && rm -rf /var/cache/*

# 배시 설치
#RUN apk add --no-cache bash

# 언어 설정
ENV LANG=ko_KR.UTF-8 \
    LANGUAGE=ko_KR.UTF-8

# 시간대 설정
RUN apk --no-cache add tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone

WORKDIR /app

# nestjs 설정
RUN npm install -g npm

# package*.json 파일 변경감지하여 이후 구문을 실행함
COPY ./configs/vite.conf/package*.json .
RUN rm -rf node_modules
RUN npm install