FROM postgres:15.10-bookworm

RUN apt update && apt install -y wget unzip

# 한글 폰트 설치
RUN apt install -y fonts-nanum
#RUN mkdir -p /usr/share/fonts/nanumfont
#RUN wget http://cdn.naver.com/naver/NanumFont/fontfiles/NanumFont_TTF_ALL.zip
#RUN unzip NanumFont_TTF_ALL.zip -d /usr/share/fonts/nanumfont
#RUN fc-cache -f && rm -rf /var/cache/*

# 시간대 설정
RUN apt install -y tzdata && \
        cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
        echo "Asia/Seoul" > /etc/timezone

# DB 설정
ENV TZ=Asia/Seoul
ENV POSTGRES_INITDB_ARGS="--encoding=UTF-8"
ENV ALLOW_IP_RANGE=0.0.0.0/0

# pgvector 설치
RUN apt install -y postgresql-15-pgvector