apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://bws_tempo:8000
    version: 1
    editable: false
    uid: tempo
  - name: Loki
    type: loki
    access: proxy
    url: http://bws_loki:3100
    version: 1
    editable: false
    isDefault: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id=(\w+)
          name: TraceID
          url: "$${__value.raw}"